apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 02-test-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: >- 
      ServerSideDiff=true,
      IncludeMutationWebhook=true 
spec:
  project: default
  sources:
  # This app itself
  - repoURL: git@github.com:graysievert-lab/experiment-k8s-bootstrapping-applicationset-generator-matrix-git-file-list.git
    targetRevision: HEAD 
    path: "."
  
  # applicationsets
  - repoURL: git@github.com:graysievert-lab/experiment-k8s-bootstrapping-applicationset-generator-matrix-git-file-list.git
    targetRevision: HEAD 
    path: "appsets"

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=orphan # Supported policies are background, foreground and orphan.
      - ApplyOutOfSyncOnly=true # Only sync out-of-sync resources, rather than applying every object in the application
      - ServerSideApply=true      
    retry:
      limit: -1